// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("nfdi-helpdesk")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","21.02.2022")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "nfdi-helpdesk"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "21.02.2022"
