// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("nfdi-helpdesk")>]
[<assembly: AssemblyVersionAttribute("1.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","27.05.2022")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "nfdi-helpdesk"
    let [<Literal>] AssemblyVersion = "1.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "27.05.2022"
